emailing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('mail', views.index, name="index"),
]

emploi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

handler404 = "research.views.handler404"
handler500 = "research.views.handler500"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("research.urls")),
    path('emailing/', include("emailing.urls")),
]

urlpatterns += (
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

research/urls.py
from django.urls import path
from . import views

app_name="research"

urlpatterns = [
    path('', views.index, name="index"),
    path('alert/<int:id>', views.alert, name="alert"),
    path('p/<str:base64>', views.confirm_email, name="confirm_email"),
    path('preference', views.preference, name="preference"),
]

emailing/models.py
from django.db import models

# Create your models here.

research/models.py
from django.db import models
from django.contrib import admin

class UserPreference(models.Model):
    REGIONS=(
        ('paris', 'Paris'),
        ('herault', 'Montpellier'),
        ('toulouse', 'Toulouse'),
        ('autre', 'Autre'),
    )
    LANG=(
        ('python', 'Python'),
        ('php', 'Php'),
        ('java', 'Java'),
        ('autre', 'Autre')
    )
    region = models.CharField(max_length=100, choices=REGIONS)
    lang = models.CharField(max_length=100, choices=LANG)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.lang} - {self.region}"


class UserPreferenceAdmin(admin.ModelAdmin):
    list_display = ['region', 'lang', 'create_at']

class UserEmail(models.Model):
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=50)
    valid = models.BooleanField(default=False)
    user_preference = models.ForeignKey(UserPreference, on_delete=models.DO_NOTHING, null=True)
    create_at = models.DateTimeField(auto_now_add=True, null=True)
    
    def preference(self):
        return f"{self.user_preference.lang} - {self.user_preference.region}"

class UserEmailAdmin(admin.ModelAdmin):
    list_display = ['name', 'email', 'code', 'valid', 'preference', 'create_at']

research/forms.py
from django import forms
from . models import UserPreference

class UserPreferenceForm(forms.ModelForm):
    class Meta:
        model = UserPreference
        fields = ['region', 'lang']

        widgets = {
            'lang': forms.Select(attrs={'class': 'form-control'}),
            'region': forms.Select(attrs={'class': 'form-control region'}),
        }

emailing/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.conf import settings

# Create your views here.
def index(request):
    context = {}
    if request.method=="POST":
        mail = request.POST.get("mail")
        obj = request.POST.get("obj")
        text = request.POST.get("text")
        info = {
            "text" : text,
            "username" : "Toto"
        }
        template_email = render_to_string('emailing/email.html', info)
        email = EmailMessage(obj, template_email, settings.EMAIL_HOST_USER, [mail])
        email.content_subtype = "html"
        # email.attach_file(f"{settings.MEDIA_ROOT}/cv_makan.pdf")
        email.fail_silently = False
        try:
            email.send()
            context["success"] = "Message envoyé."
        except:
            context["error"] = "Message non envoyé. Réessayer"
    return render(request, "emailing/index.html", context)

research/views.py
from django.shortcuts import render, redirect
from . import func
from . scrapper import HelloWork
from . models import UserEmail, UserPreference
from . forms import UserPreferenceForm
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.conf import settings
import logging

log = logging.getLogger('log')

# Create your views here.
def index(request):
    if request.method=="POST":
        keyword = request.POST.get("keyword")
        location = request.POST.get("location")
        emploi = HelloWork().scrap(keyword, location)
        return render(request, 'research/result.html', {"data" : emploi})

    return render(request, 'research/index.html')

def alert(request, id):
    context = {}
    try:
        user_preference = UserPreference.objects.get(pk=id)
    except:
        return handler404(request, 404)

    if request.method=="POST":
        email = request.POST.get("email")
        name = request.POST.get('name')
        code = func.code(8)
        useremail = UserEmail(email=email, user_preference=user_preference, name=name, code=code, valid=False)
        try:
            useremail.save()
            user_id_base_64 = urlsafe_base64_encode(str(useremail.id).encode('utf-8'))
            host = request.META.get('HTTP_HOST')
            info = {
                'username' : name,
                'code' : code,
                'protocol' : 'http://',
                'host' : host,
                'path' : f'/p/email-confirmation-{user_id_base_64}'
            }
            template_email = render_to_string('research/email.html', info)
            email = EmailMessage("Votre code de vérification", template_email, settings.EMAIL_HOST_USER, [email])
            email.content_subtype = "html"
            email.fail_silently = False
            try:
                email.send()
                return redirect(f"/p/email-confirmation-{user_id_base_64}")
            except Exception as e:
                log.error(e)
        except Exception as e:
            log.error(e)
            message = "Oups erreur inconnu! Il se peut que cet email exist déjà. Éssayer avec un autre email."
            context["message"] = message

    return render(request, "research/alert.html", context)

def confirm_email(request, base64):
    context = {}
    id_base64 = base64.split("-")[2]
    try:
        user = UserEmail.objects.get(pk=urlsafe_base64_decode(id_base64))
    except:
        return handler404(request, exception=404)
    else:
        if user.valid == True:
            context['valided'] = "Email déjà validé"
        else:
            if request.method=="POST":
                code = request.POST.get("code")
                clean_code = code.strip()
                if user.code == clean_code:
                    user.valid=True
                    user.save()
                    context['success'] = "Mail validé !"
                else:
                    message = 'Code incorrect'
                    context['message'] = message
        context['username'] = user.name
    return render(request, "research/confirm_email.html", context)

def preference(request):
    if request.method=="POST":
        form = UserPreferenceForm(request.POST)
        if form.is_valid():
            form.save()
            preference = UserPreference.objects.last()
            return redirect(f"/alert/{preference.id}")

    context = {'form' : UserPreferenceForm}
    return render(request, "research/preference.html", context)

def handler404(request, exception):
    return render(request, "research/errors/404.html", status=404)

def handler500(request):
    return render(request, "research/errors/500.html", status=500)

emailing/templates/emailing/email.html
<h2>Bonjour {{ username }}</h2>

<p>{{ text }}</p>

Si vous recevez ce message par erreur, veuillez l'ignorer.

Cordialement.

emailing/templates/emailing/index.html
{% extends 'layout/base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-4 mt">
            {% if user.is_authenticated %}
                <h1 class="text-success text-center">Envoie d'email</h1> <br /> 
                {% if success %}
                    <p class="text-success">{{ success}}</p>
                {% elif error %}
                    <p class="text-danger">{{ error }}</p>
                {%  endif %}
                <form method="POST" action=""> {% csrf_token %}
                    <input name="mail" id="research" class="form-control" required placeholder="adresse mail"> <br />
                    <input name="obj" id="research" class="form-control" required placeholder="Objet de votre mail. Pourquoi vous envoyez cet mail ?"> <br />
                    <textarea rows="10" cols="50" type="text" name="text" id="research" class="form-control" required placeholder="Votre text"></textarea> <br />
                    <button class="btn btn-success research-btn home-btn" type="submit">Envoyer</button>
                    <br /> <br />

                    <div class="d-flex justify-content-center">
                        <div class="spinner-border sp" style="width: 5rem; height: 5rem;" role="status">
                        <span class="visually-hidden">Loading...</span>
                        </div>
                    </div>
                </form>
            {% else %}
                <h1 class="text-warning text-center">Vous n'êtes pas connecté.</h1> <br /> 
            {% endif %}
        </div>
    </div>
{% endblock %}

research/templates/research/alert.html
{% extends 'layout/base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-4 mt">
            <p class="text-danger">{{ message }}</p>
            <form action="" method="POST">{% csrf_token %}
                <div class="mb-3">
                  <label for="email" class="form-label">Votre mail</label>
                  <input type="email" placeholder="exemple@gmail.com" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required>
                  <div id="emailHelp" class="form-text">Vous allez recevoir un code de confirmation.</div>
                </div>
                <div class="mb-3">
                  <label for="name" class="form-label">Votre nom</label>
                  <input type="text" placeholder="Chloe" name="name" class="form-control" id="exampleInputPassword1" required>
                </div>
                <div class="mb-3 form-check">
                  <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                  <label class="form-check-label" for="exampleCheck1">CGU</label>
                </div>
                <button type="submit" class="btn btn-primary research-btn">Je valide</button>
            </form>
        </div>
    </div>
{% endblock %}

research/templates/research/confirm_email.html
{% extends 'layout/base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-4 mt">
            <h5>Veuillez valider votre email</h5>
            <p>Un code de vérification vous est envoyé à votre adresse email</p>
            <hr>
            <p class="text-danger">{{ message }}</p>
            <p class="text-success">{{ success }}</p>
            <p class="text-warning">{{ valided }}</p>
            <form action="" method="POST">{% csrf_token %}
                <div class="mb-3">
                  <label for="code" class="form-label">Code de confirmation</label>
                  <input type="text" placeholder="kBd%JM!e" name="code" class="form-control" id="exampleInputPassword1" required>
                </div>
                <button type="submit" class="btn btn-primary research-btn">Je confirme</button>
            </form>
        </div>
    </div>
{% endblock %}

research/templates/research/email.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email</title>
</head>
<body>
    <h1>Bonjour {{ username }}</h1>
    <p>
        Merci pour votre inscription à notre newsletter !
        Notre objectif, c'est de vous aider dans votre recherche d'emploi.
        Veuillez confirmer votre adresse email. 
    </p>
    <h2>Votre code est > <mark>{{ code }}</mark></h2>
    <p>Vous pouvez à tout moment vous rendre <a href="{{ protocol }}{{ host }}{{ path }}">{{ protocol }}{{ host }}{{ path }}</a> pour confirmer votre email.</p>
    <p style="color: yellow;">Si vous recevez ce message par erreur, veuillez l'ignorer.</p>
    <br />
    <p>Cordialement</p>
</body>
</html>

research/templates/research/index.html
{% extends 'layout/base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-4 mt">

            <h1 class="text-success text-center">Mon emploi</h1> <br /> 
            <form method="POST" action=""> {% csrf_token %}
                <input name="keyword" id="research" class="form-control" required placeholder="Que cherchez-vous ? Ex : développeur python"> <br />
                <input name="location" id="research2" class="form-control" required placeholder="Vous cherchez dans quelle ville ? Ex :  Paris"> <br />
                <button class="btn btn-success research-btn home-btn" type="submit">Rechercher</button>
                <br /> <br />

                <div class="d-flex justify-content-center">
                    <div class="spinner-border sp" style="width: 5rem; height: 5rem;" role="status">
                      <span class="visually-hidden">Loading...</span>
                    </div>
                  </div>
            </form>
        </div>
    </div>
{% endblock %}

research/templates/research/preference.html
{% extends 'layout/base.html' %} {% load crispy_forms_tags %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-4 mt">
            <h1 class="text-center">Préference</h1> <br /> 
            <form method="POST" action=""> {% csrf_token %}
                {{ form|crispy }} <br />
                <button type="submit" class="btn btn-primary research-btn">Continuer</button>
            </form>
        </div>
    </div>
{% endblock %}

research/templates/research/result.html
{% extends 'layout/base.html' %}

{%  block content %}

    <div class="row justify-content-center">
        <div class="col-md-4 mt-result">
            <form method="POST" action=""> {% csrf_token %}
                <input name="keyword" id="research" class="form-control" required placeholder="Que cherchez-vous ? Ex: développeur python "> <br />
                <input name="location" id="research2" class="form-control" required placeholder="Vous cherchez dans quelle ville ? Ex :  Paris"> <br />
                <button class="btn btn-success research-btn" type="submit">Rechercher</button>
            </form>  <br />  <br /> <hr class="hr"> <br />  <br />

            <div class="d-flex justify-content-center">
                <div class="spinner-border sp" style="width: 5rem; height: 5rem;" role="status">
                  <span class="visually-hidden">Loading...</span>
                </div>
            </div>

            <h1 class="text-success">Resultats ({{ data|length }}) annonces.</h1> <br /> 
            {% for emploi in data %}
                
                <div class="card">
                    <div class="card-header bg-success text-white">
                       Publié le {{ emploi.date }}
                    </div>
                    <div class="card-body">
                        <h2 class="card-title">{{ emploi.title }}</h2>
                        <h6 class="card-subtitle mb-2 text-muted">{{ emploi.contrat }}, {{ emploi.city }}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">{{ emploi.minititre }}</h6>
                        <p class="card-text">{{ emploi.detail }}</p>
                        <a href="{{ emploi.link }}" class="btn btn-success research-btn" target="_blank">Postuler</a>
                    </div>
                </div>
                <br />
                
            {% endfor %}
        </div>
    </div>

    <br /> <br /> <br /> 

    <!-- {{ data }} -->
{% endblock %}

templates/layout/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
        <title>Recherche d'emploi</title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg fixed-top bg-success">
      <div class="container-fluid">
        <a class="navbar-brand text-white" href="{% url 'research:index' %}">Mon Emploi</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active text-warning" aria-current="page" href="/preference">Créer une alerte</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      {% block content %} {% endblock %}
    </div>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
  <footer style="color: black; text-align: center; padding: 5.5px" class="footer">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">Power by PYTHON &copy; {% now 'Y' %} | <a href="https://www.makandianka.org" target="_blank">Developer</a></div>
      <div class="col-md-4"></div>
    </div>
    
  </footer>
</html>